address:
- 6075 S. Innovation Way West
- Mesa, AZ 85212

phone: 480-727-1127

email: Thomas.Sugar@asu.edu

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: page
      image:
        feature: robotics_lab-10.jpg
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

base_path: "/hmil"

kramdown:
  input: GFM
  auto_ids: true
highlighter: pygments

organization_name: Human Machine Integration Lab
title: Human Machine Integration Lab

exclude: [vendor]

menu:
  - name: Projects
    link: projects
  - name: Publications
    link: publications
  - name: People
    link: people

tags: a,b,c,d
